### ISSUE TITLE
Is this project still being maintained? 

### ISSUE THREAD

**Issue by cburman01** [mendrugory/signalrex#2]
I don't see the package on Hex.  @mendrugory Are you still working on this?  I just want to use this library to connect to a signalrHub to simply check the server.

**Comment by mendrugory** [comment]
Hi,
The project is not in Hex because I don't like to publish libraries without tests. The project is not maintained at this moment because I am not using it.

**Comment by cburman01** [comment]
@mendrugory Thanks for your reply. After I digged into it a bit, I found that our servers are using Kerberos which I don't think will work with elixir.  Sadly I will move on.
